# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
