# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_todo_mydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='mydate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
