# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180427_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='mydate',
        ),
    ]
