# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_remove_todo_mydate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together=set([('user', 'text')]),
        ),
    ]
