# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20180427_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
