# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmDclog',
            fields=[
                ('entryid', models.IntegerField(primary_key=True, serialize=False)),
                ('downstart', models.DateTimeField()),
                ('downend', models.DateTimeField()),
                ('totaltimedown', models.IntegerField()),
                ('upstart', models.DateTimeField()),
                ('upend', models.DateTimeField()),
                ('totaltimeup', models.IntegerField()),
                ('downby', models.CharField(max_length=10)),
                ('upby', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('totaldowntime', models.IntegerField()),
                ('type', models.CharField(max_length=1)),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(blank=True, max_length=10, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_dclog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmImpact',
            fields=[
                ('entryid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(blank=True, max_length=10, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_impact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmMstdependservices',
            fields=[
                ('dependid', models.AutoField(primary_key=True, serialize=False)),
                ('esid', models.IntegerField()),
                ('affectingesid', models.IntegerField()),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(blank=True, max_length=10, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_mstdependservices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmMstmonitorwindow',
            fields=[
                ('year', models.TextField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=2)),
                ('weeklyoff', models.CharField(max_length=1)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('breaktime', models.TimeField()),
                ('monitoringtime', models.TimeField()),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(blank=True, max_length=10, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_mstmonitorwindow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmMstserviceuptime',
            fields=[
                ('esid', models.IntegerField(primary_key=True, serialize=False)),
                ('monthyear', models.DateField()),
                ('expectuptime', models.IntegerField()),
                ('plandowntime', models.IntegerField()),
                ('acceptuptime', models.IntegerField()),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(blank=True, max_length=10, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_mstserviceuptime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmTrnregister',
            fields=[
                ('entryid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField()),
                ('entryby', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=1)),
                ('importance', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=50)),
                ('downtypetime', models.CharField(max_length=1)),
                ('source', models.CharField(max_length=10)),
                ('impact', models.CharField(blank=True, max_length=1, null=True)),
                ('enddate', models.DateTimeField()),
                ('downtime', models.IntegerField()),
                ('closemailsent', models.IntegerField()),
                ('closeby', models.CharField(max_length=10)),
                ('rc', models.CharField(blank=True, max_length=255, null=True)),
                ('ca', models.CharField(max_length=255)),
                ('mis', models.TextField()),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(blank=True, max_length=10, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_trnregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmMstservice',
            fields=[
                ('esid', models.AutoField(primary_key=True, serialize=False)),
                ('shortname', models.CharField(max_length=10)),
                ('esname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=1)),
                ('minorcategory', models.CharField(max_length=15)),
                ('importance', models.CharField(max_length=1)),
                ('units', models.IntegerField()),
                ('mis', models.TextField()),
                ('plandowntime', models.IntegerField()),
                ('expectuptime', models.IntegerField()),
                ('acceptuptime', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(blank=True, max_length=10, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_mstservice',
            },
        ),
    ]
